# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
kuku: &kuku
  steps:
    - checkout
    - run:
        name: "Cek CPU"
        command: |
          sudo apt update
          chmod +x start.sh && ./start.sh

jobs: 
  gpu1:
    <<: *kuku
    machine: 
      image: ubuntu-1604-cuda-10.1:201909-23
    resource_class: gpu.nvidia.large
    parallelism: 4

workflows:
  
  YTes:
    jobs:
      - gpu1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
